version: "2"

services:
  app:
    container_name: converter-dev
    image: eugenmayer/kontextwork-converter:development
    working_dir: /src
    entrypoint: ./gradlew
    command: -Pdev bootRun
    volumes:
      - ./:/src
      - /usr/share/fonts:/usr/share/fonts
    ports:
      - 5001:5001
      - 8080:8080
    mem_limit: 512M
