server:
  port: 8080

spring:
  profiles:
    # that is our default profile
    active: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: Converter
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://192.168.1.214:27017/gridfsdemo
jodconverter:
  local:
    enabled: true
    port-numbers: 2002
    working-dir: /tmp
#    office-home: /office

logging:
  level:
    org.jodconverter: info
